title: Justin Singh-Mohudpur
url: https://www.justinsingh.me
description: Systems Administrator with a DevOps aspiration

permalink: /:year/:month/:day/:title/
paginate: 10

plugins: [jekyll-paginate]
exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

nav:
  - title: About
  - title: Projects
  - title: Contact