---
title: "Hello R Markdown"
date: 2015-07-23T21:13:14-05:00
categories: ["R"]
tags: ["R Markdown", "plot", "regression"]
---

```{r setup, include=FALSE}
library(tidyverse)
library(sf)
library(viridis)
library(readxl)
library(showtext)
library(USAboundaries)
library(USAboundariesData)
knitr::opts_chunk$set(collapse = TRUE, warning = FALSE, message = FALSE)
```

# Loading Data

```{r, echo = FALSE}
# Map theme edited from:
# https://timogrossenbacher.ch/2016/12/beautiful-thematic-maps-with-ggplot2-only/
font_add_google("Ubuntu")
theme_map <- function(...) {
    theme_minimal() +
        theme(
            text = element_text(family = "Ubuntu", color = "#22211d"),
            axis.line = element_blank(),
            axis.text.x = element_blank(),
            axis.text.y = element_blank(),
            axis.ticks = element_blank(),
            axis.title.x = element_blank(),
            axis.title.y = element_blank(),
            panel.grid.major = element_blank(),
            panel.grid.minor = element_blank(),
            plot.background = element_blank(),
            plot.title = element_text(
                hjust = 0.5,
                color = "#4e4d47",
                size = 24
            ),
            panel.background = element_blank(),
            legend.background = element_rect(fill = "#f5f5f2", color = NA),
            legend.position = "bottom",
            panel.border = element_blank(),
            ...
        )
}

# Getting USA data
states <- USAboundaries::us_states() %>%
    st_transform(5070)

usa_outline <- states %>%
    st_union() %>%
    st_cast("MULTILINESTRING")

url = "https://raw.githubusercontent.com/nytimes/covid-19-data/master/us-counties.csv"
covid <- readr::read_csv(url)

counties <- USAboundaries::us_counties() %>%
    select(name, state_name, geometry) %>%
    filter(!(state_name %in% c("Hawaii", "Alaska", "Puerto Rico"))) %>%
    right_join(covid,
               by = c("name" = "county", "state_name" = "state")) %>%
    st_transform(5070)

# Pre-shrinking dataset
# population_dir = "data/PopulationEstimates.xls"
# population_estimates <- readxl::read_excel(population_dir)
# population_estimates <- setNames(population_estimates, population_estimates[2, ]) # Set headers
# population_estimates <- population_estimates[-c(1:2), ] # Remove first two rows
# state_list <- data.frame(
#   State_Full = state.name,
#   State = state.abb
# )
# population_estimates <- population_estimates %>%
#   mutate(Area_Name = str_remove_all(Area_Name, regex(".County"))) %>%
#   left_join(state_list, by = "State") %>%
#   select(State_Full, Area_Name, POP_ESTIMATE_2019, POP_ESTIMATE_2018)
# write.csv(population_estimates, "data/population_estimates.csv")

population_dir <- "data/population_estimates.csv"
population_estimates <- readr::read_csv(population_dir)

counties_with_pop <- population_estimates %>%
    select(State_Full, Area_Name, POP_ESTIMATE_2019, POP_ESTIMATE_2018) %>%
    setNames(c("state_name",
        "name",
        "population_estimate_2019",
        "population_estimate_2018")) %>%
    right_join(counties, by = c("state_name", "name")) %>%
    # Use 2019 estimates; if returns NA, then use 2018 estimates.
    mutate(
        cases_per_capita = if_else(
        is.na(cases / as.double(population_estimate_2019)),
        cases / as.double(population_estimate_2019),
        cases / as.double(population_estimate_2018))) %>%
    st_as_sf()

ggplot() +
    geom_sf(
        data = counties_with_pop %>%
            filter(date == max(date)),
        aes(fill = cases_per_capita)
    ) +
    scale_fill_viridis(
    option = "viridis",
    direction = -1,
    name = "Confirmed COVID-19 Cases per Capita",
    trans = "log",
    guide = guide_colorbar(
        direction = "horizontal",
        barheight = unit(2, units = "mm"),
        barwidth = unit(50, units = "mm"),
        draw.ulim = F,
        title.position = "top",
        title.hjust = 0.5,
        label.hjust = 0.5)) +
    labs(
    title = "COVID-19",
    caption = "Source: NYTimes COVID-19 County Data") +
    theme_map()
```