backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

publish_mode: editorial_workflow

media_folder: "static/img"

collections:
  - name: "post"
    label: "Post"
    folder: "content/post"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
        - {label: "Layout", name: "layout", widget: "hidden", default: "post"}
        - {label: "Title", name: "title", widget: "string"} # Title
        - {label: "Date", name: "date", widget: "datetime"} # Date
        - {label: "Body", name: "body", widget: "markdown"}
